### ISSUE TITLE
Document popular design systems

### ISSUE THREAD

**Issue by thereisnogabe** [decentralized-identity/wallet-rendering#20]
From @OR13 

> - [Microsoft](https://www.microsoft.com/design/fluent/#/)
> - [Google](https://material.io/design)
> - [Amazon ](https://abduzeedo.com/amazon-web-services-design-system)
> - [Apple](https://developer.apple.com/design/)

https://github.com/decentralized-identity/credential-manifest/issues/29

**Comment by andorsk** [comment]
-  Juan: Suggestion to add a non-normative link to the abstract.

**Comment by bumblefudge** [comment]
* Andor: JSON Form should also be mentioned in a prior art section if one is added!
