### ISSUE TITLE
Question: where would one point to a wallet rendering file?

### ISSUE THREAD

**Issue by haarts** [decentralized-identity/wallet-rendering#30]
First of all: the discussion around this subject was exactly what we needed in our project. I'm glad I do not have to reinvent the wheel!

I don't have a question about the definition itself but I wonder _where_ I should reference or include this? Should this be part of a VC or part of a schema? Or something else entirely? In other words: how would a wallet find out about these display hints?

**Comment by ankurdotb** [comment]
We have a suggestion for this, which is to store them as [DID-Linked Resources](https://docs.cheqd.io/identity/credential-service/did-linked-resources). Note that this is not a standard/specification yet, just a suggestion on how to flexibly be able to define assets like schemas, wallet rendering files, images etc and have them resolvable via a DID query.

**Comment by ankurdotb** [comment]
This is by no means a specification/standard yet, but on our DID method one of the techniques we've been exploring and wanna get standardised is to reference such assets (such as schemas, wallet rendering files, images etc) using DID queries, which could then resolve to an underlying centralised storage, decentralised storage, or ledger. We call this idea ["DID-Linked Resources"](https://docs.cheqd.io/identity/credential-service/did-linked-resources/understanding-dlrs/context).

Using DID queries uses to resolve to a target is kinda like how `service` queries currently work, except `service` is only allowed for, well, services and not files. But semantically the technique is similar.

I know various people in the community have made their own efforts for wallet rendering, but AFAIK, I don't know a specific property per-se in VC data model spec that allows for defining things like wallet rendering file. So for now, we use an `image` property under `credentialSubject` or `issuer` to link specific sections of a VC to an image to render.

There's probably a need for describing this in a smarter way, e.g., even being able to describe multiple rendering formats like static image, Apple Wallet pass file, Google Wallet pass file etc.
