### ISSUE TITLE
Support mapping array values (lens)

### ISSUE THREAD

**Issue by JaceHensley** [decentralized-identity/wallet-rendering#5]
I'm not quite sure how this would look but the idea is to allow displaying an array of mapped items. For example if you have the following JSON:

```json5
{
  "things": [
    {
      "value": "first"
    },
    {
      "value": "second"
    }
  ]
}
```

you may want the wallet to display:

```
Value of Things: first, second
```

**Comment by brentzundel** [comment]
closing as subset of #4
