### ISSUE TITLE
Display Mapping Object - Schema Type for Images

### ISSUE THREAD

**Issue by sudeshrshetty** [decentralized-identity/wallet-rendering#7]
I noticed that [Schema types](https://identity.foundation/credential-manifest/wallet-rendering/#type-specific-configuration) in Display Mapping Object are missing image formats which can potentially be part of a given verifiable credential.

For Example: [image](https://w3c-ccg.github.io/citizenship-vocab/#image) of card holder in [Citizenship Vocabulary](https://w3c-ccg.github.io/citizenship-vocab) which can also contain ImageObject.

I would like to introduce binaries as one of the schema formats which can help an application previewing credential to handle them differently.

We can support generic binary data with formats containing MIME types or just image MIME types [Registration at IANA](https://www.iana.org/assignments/media-types/media-types.xhtml#image).

Example: 

Credential Display object 

```
"schema": {
          "type": "string",
          "format": "image/png"
        }
```

sample credential containing png image binary
```
.
.
"credentialSubject": {
    "id": "did:example:b34ca6cd37bbf23",
    "type": [
      "PermanentResident",
      "Person"
    ],
    "givenName": "JOHN",
    "familyName": "SMITH",
    "gender": "Male",
    "image": "data:image/png;base64,iVBORw0KG...................................",
    "residentSince": "2015-01-01",
    "lprCategory": "C09",
    "lprNumber": "999-999-999",
    "commuterClassification": "C1",
    "birthCountry": "Bahamas",
    "birthDate": "1958-07-17"
  }
  .
  .
```

**Comment by bumblefudge** [comment]
Discussed on today's call.  A third option would be to lean on JSON Schema's 
[non-JSON data handling](https://json-schema.org/understanding-json-schema/reference/non_json_data.html?highlight=image), which puts the whole binary blob into the value and describes the type on the schema level (see [examples](https://json-schema.org/understanding-json-schema/reference/non_json_data.html?highlight=image))

**Comment by bumblefudge** [comment]
^ This doesn't have to exclude a URI-based possibility; after WR has a stable version published, we can return to this with a concrete PR

**Comment by sudeshrshetty** [comment]
@bumblefudge sounds good

also, if you can share me the call details, I would also like to join and contribute.

**Comment by JaceHensley** [comment]
We talk about this in the "DIF CC Credential Manifest + Presentation Exchange Weekly (C&C WG)" every Thursday at 10:00am PT on the [DIF Calendar](https://bit.ly/dif-calendar)

**Comment by sudeshrshetty** [comment]
thanks @JaceHensley
